version: 2.1
 
jobs:
  build:
    docker:
      - image: cimg/node:23.10.0
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build/

  deploy:
    docker:
      - image: amazon/aws-cli
    steps:
      - run:
          name: Install tar
          command: yum install -y tar gzip
      - attach_workspace:
          at: /workspace
      - run:
          name: Configure AWS Credentials
          command: |
            aws configure set aws_access_key_id $MY_ENV_VAR
            aws configure set aws_secret_access_key $MY_ENV_VAR1
      - run: aws s3 sync /workspace s3://node-task-03 --delete
 
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build